source/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('webapp.urls'))
]

source/webapp/urls.py
from django.urls import path
from webapp.views.base import IndexView, IndexRedirectView
from webapp.views.products import ProductDetail, ProductUpdateView, ProductDeleteView, ProductCreateView
from webapp.views.product_in_cart import CartCreateView, CartDetail
from webapp.views.order import OrderCreateView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("product/", IndexRedirectView.as_view(), name='task_index_redirect'),
    path("product/add/", ProductCreateView.as_view(), name='product_add'),
    path("product/<int:pk>", ProductDetail.as_view(), name='product_detail'),
    path("product/<int:pk>/update/",
         ProductUpdateView.as_view(), name='product_update'),
    path("product/<int:pk>/delete/",
         ProductDeleteView.as_view(), name='product_delete'),
    path("product/<int:pk>/confirm_delete/",
         ProductDeleteView.as_view(), name='confirm_delete'),
    path("cart/add/<int:pk>/", CartCreateView.as_view(), name='cart_add'),
    path("cart/", CartDetail.as_view(), name='cart_detail'),
    path("order/add/", OrderCreateView.as_view(), name='order_add'),
]

source/webapp/models/categories.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name="Категория"
        )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Время и дата создания"
        )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Время и дата обновления"
        )
    is_deleted = models.BooleanField(
        verbose_name='удалено',
        null=False,
        default=False
    )

    def __str__(self):
        return self.name

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

source/webapp/models/orders.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from webapp.models.products import Product

# Create your models here.


class Order(models.Model):
    product = models.ManyToManyField(
        to='webapp.Product',
        related_name='orders',
        blank=False,
        null=False
    )
    quantity = models.IntegerField(
        validators=[MinValueValidator(0)],
        null=False,
        blank=False,
        verbose_name="Остаток"
        )
    user_name = models.CharField(
        max_length=300,
        null=False, blank=False,
        verbose_name="Имя",
        default=1
    )
    contact = models.CharField(
        max_length=300,
        null=False, blank=False,
        verbose_name="Телефон"
    )
    address = models.CharField(
        max_length=300,
        null=False, blank=False,
        verbose_name="Телефон"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания")

    is_deleted = models.BooleanField(
        verbose_name='удалено',
        null=False,
        default=False
    )

    def __str__(self):
        return f"{self.product} - {self.quantity}"

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

source/webapp/models/product_in_cart.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from webapp.models.products import Product

# Create your models here.


class Product_in_cart(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.RESTRICT, 
        null=False,
        blank=False,
        default=1
        )
    quantity = models.IntegerField(
        validators=[MinValueValidator(0)],
        null=False,
        blank=False,
        verbose_name="Остаток"
        )
    is_deleted = models.BooleanField(
        verbose_name='удалено',
        null=False,
        default=False
    )

    def __str__(self):
        return f"{self.product} - {self.quantity}"

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

source/webapp/models/products.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone
from webapp.models.categories import Category

# Create your models here.


class Product(models.Model):
    name = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name="Имя товара"
        )
    description = models.TextField(
        max_length=3000,
        null=True, blank=True,
        verbose_name="Описание товара"
        )
    image = models.CharField(
        max_length=300,
        null=False, blank=False,
        verbose_name="Фото товара"
        )
    category = models.ForeignKey(
        Category,
        on_delete=models.RESTRICT, 
        null=False,
        blank=False,
        default=1
        )
    product_left = models.IntegerField(
        validators=[MinValueValidator(0)],
        null=False,
        blank=False,
        verbose_name="Остаток"
        )
    price = models.DecimalField(
        validators=[MinValueValidator(0)],
        max_digits=7,
        decimal_places=2,
        null=False,
        blank=False,
        verbose_name="Стоимость"
        )
    is_deleted = models.BooleanField(
        verbose_name='удалено',
        null=False,
        default=False
    )

    def __str__(self):
        return f"{self.title} - {self.description}"

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

source/webapp/forms.py
from django import forms
from webapp.models import Product, Product_in_cart, Order
from django.core.validators import BaseValidator, MinValueValidator


class CustomMaxLenValidator(BaseValidator):
    def __init__(self, limit_value):
        message = 'Максимальная длина поля %(limit_value)s. Выввели %(show_value)s символов'
        super().__init__(limit_value=limit_value, message=message)

    def compare(self, value, limit_value):
        return value > limit_value

    def clean(self, value):
        return len(value)


class CustomMinLenValidator(BaseValidator):
    def __init__(self, limit_value):
        message = 'Минимальная длина поля %(limit_value)s. Выввели %(show_value)s символов'
        super().__init__(limit_value=limit_value, message=message)

    def compare(self, value, limit_value):
        return value < limit_value

    def clean(self, value):
        return len(value)


class ProductForm(forms.ModelForm):
    name = forms.CharField(
        max_length=200,
        label='Имя товара',
        validators=(CustomMinLenValidator(2), CustomMaxLenValidator(200))
    )
    description = forms.CharField(
        max_length=3000,
        label='Описание товара',
        validators=(CustomMinLenValidator(2), CustomMaxLenValidator(3000))
    )
    product_left = forms.IntegerField(validators=[MinValueValidator(0)])

    class Meta:
        model = Product
        fields = ['name', 'description', 'image',
                  'category', 'product_left', 'price']
        labels = {
            'name': 'Имя товара',
            'description': 'Описание товара',
            'image': 'Фото товара',
            'category': 'Категория',
            'product_left': 'Остаток',
            'price': 'Стоимость'
        }


class Add_in_cart_Form(forms.ModelForm):
    quantity = forms.IntegerField(
        label='Количество',
        validators=[MinValueValidator(0)]
    )

    class Meta:
        model = Product_in_cart
        fields = ['quantity',]
        labels = {
            'quantity': 'Количество',
        }


class OrderForm(forms.ModelForm):
    user_name = forms.CharField(
        max_length=200,
        label='Имя',
        validators=(CustomMinLenValidator(2), CustomMaxLenValidator(200))
    )

    class Meta:
        model = Order
        fields = ['user_name', 'contact', 'address']
        labels = {
            'user_name': 'Имя пользователя',
            'contact': 'Телефон',
            'address': 'Адрес',
        }


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20, required=False, label='Найти')

source/webapp/views/base.py
from webapp.models import Product
from django.views.generic import ListView, RedirectView
from webapp.forms import SearchForm
from django.db.models import Q
from django.utils.http import urlencode


class IndexView(ListView):
    template_name = 'index.html'
    model = Product
    context_object_name = "products"
    ordering = ['category', 'name']
    queryset = Product.objects.exclude(product_left__lt=1)
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_queryset(self):
        queryset = super().get_queryset().exclude(is_deleted=True)
        if self.search_value:
            query = Q(name__icontains=self.search_value) | Q(
                description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context


class IndexRedirectView(RedirectView):
    pattern_name = 'index'

source/webapp/views/order.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from webapp.models import Order
from webapp.forms import OrderForm


class OrderCreateView(CreateView):
    pass

source/webapp/views/product_in_cart.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DeleteView, CreateView, UpdateView, ListView

from webapp.models import Product, Product_in_cart
from webapp.forms import Add_in_cart_Form

from django.db.models import F, Sum, ExpressionWrapper, IntegerField


class CartCreateView(CreateView):
    template_name = 'product_in_cart_create.html'
    model = Product_in_cart
    form_class = Add_in_cart_Form

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        product_in_cart = form.save(commit=False)
        product_in_cart.product = product
        quantity = product_in_cart.quantity
        if quantity <= product.product_left:
            product_in_cart.save()
            return redirect('index')
        else:
            form.add_error(
                'quantity', 'На складе не достаточно товара, введите число не выше остатка')
            return self.form_invalid(form)


class CartDetail(ListView):
    template_name = 'cart_detail.html'
    context_object_name = 'product_in_cart'
    model = Product_in_cart
    paginate_by = 10
    paginate_orphans = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_per_item = Product_in_cart.objects.annotate(
            total_per_item=ExpressionWrapper(
                F('product__price') * F('quantity'), output_field=IntegerField())
        ).values('id', 'total_per_item')
        total_per_item_dict = {
            item['id']: item['total_per_item'] for item in total_per_item}
        context['total_per_item'] = total_per_item_dict
        context['overall_total'] = Product_in_cart.objects.aggregate(
            overall_total=Sum(ExpressionWrapper(
                F('product__price') * F('quantity'), output_field=IntegerField()))
        )['overall_total'] or 0

        return context

source/webapp/views/products.py
from webapp.models import Product
from webapp.forms import ProductForm
from django.views.generic import DeleteView, CreateView, UpdateView
from django.urls import reverse, reverse_lazy


class ProductCreateView(CreateView):
    template_name = 'product_create.html'
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('product_detail', kwargs={'pk': self.object.pk})


class ProductDetail(DeleteView):
    template_name = 'product.html'
    model = Product


class ProductUpdateView(UpdateView):
    template_name = 'product_update.html'
    form_class = ProductForm
    model = Product

    def get_success_url(self):
        return reverse('product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    template_name = 'product_confirm_delete.html'
    model = Product
    success_url = reverse_lazy('index')

source/webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
  <title>{% block title %}Product{% endblock %}</title>
</head>

<body>
  <div class="container">
    <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'product_add' %}">Добавить Продукт</a>
            </li>
            {% block menu %}
            {% endblock %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'cart_detail' %}"><i
                  class="fa-solid fa-cart-plus cart_icon_size"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container">
    {% block content%}{% endblock %}
  </div>
</body>

</html>

source/webapp/templates/cart_detail.html
{% extends 'base.html' %}
{% block title %}Cart{% endblock %}
{% block menu%}
{% endblock %}
{% block content%}
<div class="container text-center mt-5">
    <div class="row justify-content-around">
        {% for item in product_in_cart %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="text-start">
                        <div class="card-body">
                            <h5 class="card-title">Продукт: {{ item.product.name }}</h5>
                            <h5 class="card-title">Цена: {{ item.product.price }}₸</h5>
                            <h6 class="card-title">Количество: {{ item.quantity }}</h6>
                            <h6 class="card-title">Сумма: {{ total_per_item.item.id }}₸</h6>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Продукты не найдены</p>
        {% endfor %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="text-start">
                    <div class="card-body">
                        <h5 class="card-title">Итоговая сумма: {{ overall_total }}₸</h5>
                    </div>
                </div>
            </div>
        </div>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
    <div class="form mx-auto my-5 col-8">
        <h2>Заполните данные для заказа</h2>
        <form method="post" action="">
            {% csrf_token %}
            <div class="form-group">
            <label for="id_user_name">Имя:</label>
            <input type="text" class="form-control" name="user_name" id="id_user_name">
            </div>
            <div class="form-group">
            <label for="id_contact">Телефон:</label>
            <input type="text" class="form-control" name="contact" id="id_contact">
            </div>
            <div class="form-group">
            <label for="id_address">Адрес:</label>
            <input type="text" class="form-control" name="address" id="id_address">
            </div>
            <button type="submit" class="btn my-2 btn-outline-primary">Оформить заказ</button>
        </form>
    </div>


</div>
{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block menu%}
{% endblock %}
{% block content%}
<div class="container text-center mt-5">
    {% include 'partial/search.html' %}
    <div class="row justify-content-around">
        {% for product in products %}
        <div class="col-5">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ product.image }}" class="img-fluid rounded-start"
                            alt="{{ product.name }}">
                    </div>
                    <div class="col-md-8 text-start">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <div class="cart_icon">
                                    <a href="{% url 'cart_add' product.pk %}">
                                        <i class="fa-solid fa-cart-plus cart_icon_size"></i>
                                    </a>
                                </div>
                            </div>
                            <h6 class="card-title">Категория - {{ product.category }}</h6>
                            <p class="card-text">Остаток: {{ product.product_left }}</p>
                            <h5 class="card-text">Цена: {{ product.price }}₸</h5>
                            <a href="{% url 'product_detail' product.pk %}" class="btn btn-outline-primary">подробнее...</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <p>Продукты не найдены</p>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
</div>
{% endblock %}

source/webapp/templates/product.html
{% extends 'base.html' %}
{% block title %}Product{% endblock %}
{% block menu %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'product_update' product.pk %}">Редактировать Продукт</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'product_delete' product.pk %}">Удалить Продукт</a>
</li>
{% endblock %}
{% block content%}
<div class="container">
    <div class="col-8 mx-auto mt-5">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ product.image }}" class="img-fluid rounded-start" alt="{{ product.name }}">
                </div>
                <div class="col-md-8 text-start">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">Категория: {{ product.category }}</p>
                        <p class="card-text">{{ product.description }}</p>
                        <p class="card-text">Остаток: {{ product.product_left }}</p>
                        <h5 class="card-text">Цена: {{ product.price }}₸</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

source/webapp/templates/product_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Product confirm delete{% endblock %}
{% block menu %}
    <a class="nav-link" href="{% url 'product_update' product.pk %}">Редактировать продукт</a>
{% endblock %}
{% block content%}
<div class="container">
    <h1>Вы точно хотите удалить продукт?</h1>
    <div class="card mt-5">
        <img src="product.image" class="card-img-top" alt="product.name ">
        <div class="card-body">
            <h5 class="card-title">Название: {{ product.name }}</h5>
            <p>Описание: {{ product.description|linebreaks  }}</p>
            <p>Категория: {{ product.category }}</p>
            <p>Остаток: {{ product.product_left }}</p>
            <p>Стоимость: {{ product.price }}</p>
            <form action="{% url 'confirm_delete' product.pk %}" method="post">
                {% csrf_token %}
                <p><input type="submit" value="Удалить"></p>
                <p><a href="{% url 'index' %}">Отмена</a></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

source/webapp/templates/product_create.html
{% extends 'base.html' %}
{% block title %}Добавить новый продукт{% endblock %}
{% block content%}
<h1>Добавить новый продукт</h1>
<div class="form  col-8">
    <form action="{% url 'product_add' %}" method="post">
    {% include 'partial/product_form.html' with button_text='Добавить' %}
    </form>
</div>
{% endblock %}

source/webapp/templates/product_in_cart_create.html
{% extends 'base.html' %}
{% block title %}Добавить новый продукт{% endblock %}
{% block content%}
<h1>Добавить новый продукт</h1>
<div class="form  col-8">
    <form action="" method="post">
    {% include 'partial/product_form.html' with button_text='Добавить' %}
    </form>
</div>
{% endblock %}

source/webapp/templates/product_update.html
{% extends 'base.html' %}
{% block title %}Редактировать продукт{% endblock %}
{% block content%}
<h1>Редактировать продукт</h1>
<div class="form  col-8">
    <form action="{% url 'product_update' product.pk %}" method="post">
        {% include 'partial/product_form.html' with button_text='Редактировать' %}
    </form>
</div>
{% endblock %}